import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ReduxProvider from '@/store/provider'
import Header from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        {/* <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        /> */}
      </head>
      <body suppressHydrationWarning className={inter.className}>
        <ReduxProvider>
          <Header />
          <div className="flex bg-green-50 pt-[72px] min-h-screen">
            <div className="grow shrink w-full max-w-[1440px] mx-auto my-0">
              {children}
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  )
}
