import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ReduxProvider from '@/store/provider'
import Header from '@/components'

// const inter = Inter({ subsets: ['latin'] })
//${inter.className}
export const metadata: Metadata = {
  title: '요리 공유소',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        {/* <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        /> */}
      </head>
      <body suppressHydrationWarning className={`font-sans`}>
        <ReduxProvider>
          <Header />
          <div className="flex bg-[#EDF1F5] pt-[72px] min-h-screen">
            <div className="grow shrink w-full max-w-[1160px] bg-white mx-auto my-0">
              {children}
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  )
}
